// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY87rwro3QUVmKZdOnOQfXz59bYqDYAEI',
    appId: '1:318791658916:android:8e9834382fd0e1715da531',
    messagingSenderId: '318791658916',
    projectId: 'shop-main-12dfc',
    storageBucket: 'shop-main-12dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTG_U612IV4TEG7ERqYz2RSpv7PnCS3pY',
    appId: '1:318791658916:ios:1601dcf3878e46125da531',
    messagingSenderId: '318791658916',
    projectId: 'shop-main-12dfc',
    storageBucket: 'shop-main-12dfc.firebasestorage.app',
    iosBundleId: 'com.xavics.salesapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSj-tSqV91aMKvTOYjp8FYAgMgjICFjis',
    appId: '1:318791658916:web:4bf181b59eefcc5a5da531',
    messagingSenderId: '318791658916',
    projectId: 'shop-main-12dfc',
    authDomain: 'shop-main-12dfc.firebaseapp.com',
    storageBucket: 'shop-main-12dfc.firebasestorage.app',
    measurementId: 'G-L6Z9ZZ6FZL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTG_U612IV4TEG7ERqYz2RSpv7PnCS3pY',
    appId: '1:318791658916:ios:1601dcf3878e46125da531',
    messagingSenderId: '318791658916',
    projectId: 'shop-main-12dfc',
    storageBucket: 'shop-main-12dfc.firebasestorage.app',
    iosBundleId: 'com.xavics.salesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSj-tSqV91aMKvTOYjp8FYAgMgjICFjis',
    appId: '1:318791658916:web:9cbca6f86369ff355da531',
    messagingSenderId: '318791658916',
    projectId: 'shop-main-12dfc',
    authDomain: 'shop-main-12dfc.firebaseapp.com',
    storageBucket: 'shop-main-12dfc.firebasestorage.app',
    measurementId: 'G-6FJX1BVN34',
  );

}