// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8O8GAFNw9iKS9XXwNxHgMfjBBb-sm2Qw',
    appId: '1:110369730358:android:06939ad850958019e74d97',
    messagingSenderId: '110369730358',
    projectId: 'saleapp-4df13',
    storageBucket: 'saleapp-4df13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFehAsVzP2OnZy7YYcbIRSAgBVc3J9tNY',
    appId: '1:110369730358:ios:332e08bd62e02069e74d97',
    messagingSenderId: '110369730358',
    projectId: 'saleapp-4df13',
    storageBucket: 'saleapp-4df13.firebasestorage.app',
    iosBundleId: 'com.xavics.salesapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrsbJeVSx4HQT-YkThBMqFgezru6lwEcI',
    appId: '1:110369730358:web:9bd011ab96473b4fe74d97',
    messagingSenderId: '110369730358',
    projectId: 'saleapp-4df13',
    authDomain: 'saleapp-4df13.firebaseapp.com',
    storageBucket: 'saleapp-4df13.firebasestorage.app',
    measurementId: 'G-7LX166YPLP',
  );

}